name: Inueco Cinema Pipeline
on: [push]
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: 8.0.404

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Build
        run: make build
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          path: dist

      - name: Login to Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY }}
          username: ${{ secrets.CONTAINER_REGISTRY_USER }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
    
      - name: Build and push
        uses: docker/build-push-action@v6.9.0
        with:
          push: true
          tags: ${{ secrets.CONTAINER_REGISTRY }}/evas1on/inueco.cinema
            
            
      
            